// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           20
// Async Callback:                       1
// Total number of exported functions:  22

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    elven_tools_sft_minter
    (
        init => init
        upgrade => upgrade
        getCollectionTokenId => collection_token_id
        getCollectionTokenName => collection_token_name
        isPaused => paused
        getAmountPerAddressTotal => amount_per_address_total
        issueToken => issue_token
        setLocalRoles => set_local_roles
        createToken => create_token
        mint => mint
        burn => burn
        buy => buy
        giveaway => giveaway
        claimScFunds => claim_sc_funds
        setNewPrice => set_new_price
        setNewAmountLimitPerAddress => set_new_amount_limit_per_address
        pauseSelling => pause_selling
        startSelling => start_selling
        getPrice => get_price
        getTokenDisplayName => get_token_display_name
        getMaxAmountPerAddress => get_max_amount_per_address
    )
}

multiversx_sc_wasm_adapter::async_callback! { elven_tools_sft_minter }
